{% set name = "cherry-picker" %}
{% set import = "cherry_picker" %}
{% set entrypoint = "cherry_picker" %}
{% set version = "2.6.0" %}
{% set sha256 = "f6a362c450ef033090355bbee94fe3f7c600f23f0da57d27146f55700860d8f9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0]|lower }}/{{ name|lower }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - {{ entrypoint }} = {{ import }}.{{ import }}:cherry_pick_cli

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs
    - hatchling >=1.27
    - pip
  run:
    - python >={{ python_min }}
    - click >=6
    - gidgethub
    - requests
    - stamina
    - tomli >=1.1

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - {{ import }}
    - {{ import }}.{{ import }}
  commands:
    - pip check
    - {{ entrypoint }} --help
    - {{ entrypoint }} --version

about:
  home: https://github.com/python/cherry-picker
  license: Apache-2.0
  license_file: LICENSE
  summary: Backport CPython changes from main to maintenance branches
  description: |
    This tool is used to backport CPython changes from `main` into one or more
    of the maintenance branches (e.g. `3.12`, `3.11`).
    `cherry_picker` can be configured to backport other projects with similar
    workflow as CPython. See the configuration file options below for more details.
    The maintenance branch names should contain some sort of version number (`X.Y`).
    For example: `3.12`, `stable-3.12`, `1.5`, `1.5-lts`, are all supported branch
    names.
    It will prefix the commit message with the branch, e.g. `[3.12]`, and then
    open up the pull request page.
  dev_url: https://github.com/python/cherry-picker
  doc_url: https://github.com/python/cherry-picker/blob/main/README.md

extra:
  recipe-maintainers:
    - CAM-Gerlach
